language: python

python:
  - "3.7"

services: docker

install:
  - pip install -r requirements.txt

#command to run test
script :
  - python -m  unittest discover -s Tests

branches:
  only:
   - master
   - development